server:
  port: 8080

spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/game"
    username: "user name"
    password: "password"
  jpa:
    hibernate:
    ddl-auto: update